"""initial commit

Revision ID: 4c5aa18bf481
Revises:
Create Date: 2026-01-27 10:48:58.205105

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c5aa18bf481"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_type",
        sa.Column("transaction_type_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("transaction_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "currency_type",
            sa.Enum("LOLI_COINS", "LOLI_CRYSTAL", name="currencytype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("transaction_type_id"),
        sa.UniqueConstraint("transaction_name"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_change_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "balances",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("loli_coins", sa.Integer(), nullable=False),
        sa.Column("loli_crystal", sa.Integer(), nullable=False),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("loli_coins >= 0", name="ck_balances_loli_coins_nonnegative"),
        sa.CheckConstraint("loli_crystal >= 0", name="ck_balances_loli_crystal_nonnegative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="transactionstatus"),
            nullable=False,
        ),
        sa.Column(
            "purchase_category",
            sa.Enum("PRIVILEGE", "ITEM", "SERVICE", name="purchasecategory"),
            nullable=True,
        ),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            NOT (\n                transaction_type_id IN (\n                1,\n                2\n                )\n                AND purchase_category IS NOT NULL\n            )\n            ",
            name="ck_transactions_replenishment_no_category",
        ),
        sa.CheckConstraint(
            "\n            NOT (\n                transaction_type_id IN (\n                3,\n                4\n                )\n                AND purchase_category IS NULL\n            )\n            ",
            name="ck_transactions_purchase_category_required",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_transactions_amount_non_negative"),
        sa.ForeignKeyConstraint(
            ["transaction_type_id"],
            ["transaction_type.transaction_type_id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_transactions_purchase_category"),
        "transactions",
        ["purchase_category"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    op.create_index(
        op.f("ix_transactions_transaction_type_id"),
        "transactions",
        ["transaction_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_user_sessions_refresh_token_hash"),
        "user_sessions",
        ["refresh_token_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.execute(
        "\n        CREATE FUNCTION update_password_change_date()\n        RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.password_change_date = CURRENT_TIMESTAMP;\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql;\n        "
    )
    op.execute(
        "\n        CREATE TRIGGER trigger_password_change\n        BEFORE UPDATE OF password ON users\n        FOR EACH ROW\n        EXECUTE FUNCTION update_password_change_date();\n        "
    )
    op.execute(
        "\n        INSERT INTO transaction_type (transaction_type_id, transaction_name, description, currency_type) VALUES\n        (1, 'Пополнение лоли-кристаллов', 'Покупка лоли-кристаллов за реальные деньги', 'LOLI_CRYSTAL'),\n        (2, 'Пополнение лоли-коинов', 'Начисление лоли-коинов за ивенты/активность', 'LOLI_COINS'),\n        (3, 'Покупка за лоли-кристаллы', 'Покупка предметов/услуг за лоли-кристаллы', 'LOLI_CRYSTAL'),\n        (4, 'Покупка за лоли-коины', 'Покупка предметов/услуг за лоли-коины', 'LOLI_COINS');\n        "
    )
    op.execute(
        "\n        CREATE OR REPLACE FUNCTION create_balance_for_new_user()\n        RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO balances (user_id, loli_coins, loli_crystal, date_modify)\n            VALUES (NEW.user_id, 0, 0, NOW());\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql;\n        "
    )
    op.execute(
        "\n        CREATE TRIGGER after_user_insert\n        AFTER INSERT ON users\n        FOR EACH ROW\n        EXECUTE FUNCTION create_balance_for_new_user();\n        "
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trigger_password_change ON users;")
    op.execute("DROP FUNCTION IF EXISTS update_password_change_date();")
    op.execute("DROP TRIGGER IF EXISTS after_user_insert ON users;")
    op.execute("DROP FUNCTION IF EXISTS create_balance_for_new_user();")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_refresh_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_type_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_purchase_category"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("balances")
    op.drop_table("users")
    op.drop_table("transaction_type")
    # ### end Alembic commands ###
